version: '3.8'

services:
  # The FastAPI backend service
  backend:
    build: 
      context: .
      target: ""  # Uses the final stage by default
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Remove this in production for security
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # The Streamlit frontend service  
  frontend:
    build: 
      context: .
      target: ""  # Uses the final stage by default
    ports:
      - "8501:8501"
    volumes:
      - .:/app  # Remove this in production
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - API_BASE_URL=http://backend:8000
      - PYTHONPATH=/app
    command: streamlit run ui.py --server.port 8501 --server.address 0.0.0.0 --server.enableCORS false --server.enableXsrfProtection false