services:
  # The FastAPI backend service
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  # The Streamlit frontend service  
  frontend:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - backend
    environment:
      - API_BASE_URL=http://backend:8000
    command: streamlit run ui.py --server.port 8501 --server.address 0.0.0.0